apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: whoami
    patch: |-
     - op: replace
       path: /spec/replicas
       value: 3
     - op: add
       path: "/spec/template/spec/containers/0/env/0/name"
       value: "MY_NODE_NAME"
     - op: add
       path: "/spec/template/spec/containers/0/env/0/value"
       value: "test-env-2"
