apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: whoami
    patch: |-
     - op: replace
       path: /spec/replicas
       value: 2